pipeline {
    agent {
        docker {
            image 'python:3.12.0a1-slim'
        }
    }

    stages {
        stage('build') {
            when{
                changeset "**/vote/**"
            }
            steps {
                echo 'Compiling vote app'
                dir('vote') {
                    sh 'pip install --user -r requirements.txt'
                }
            }
        }
        stage('test') {
            when{
                changeset "**/vote/**"
            }
            steps {
                echo 'Running Unit Tests on vote app'
                dir('vote') {
                    sh 'nosetests -v'
                }
            }
        }
    }

    post {
        always {
            echo 'Build pipeline for vote is completed...'
        }
        failure {
            slackSend (channel: "instavote-cd", message: "Build failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        success {
            slackSend (channel: "instavote-cd", message: "Build success - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}
